/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSessionsRouteImport } from './routes/api/sessions'
import { Route as ApiDocumentsRouteImport } from './routes/api/documents'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiSessionsSessionIdRouteImport } from './routes/api/sessions.$sessionId'
import { Route as ApiDocumentsDocumentIdRouteImport } from './routes/api/documents.$documentId'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth.register'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth.login'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsRoute = ApiSessionsRouteImport.update({
  id: '/api/sessions',
  path: '/api/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsRoute = ApiDocumentsRouteImport.update({
  id: '/api/documents',
  path: '/api/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsSessionIdRoute = ApiSessionsSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => ApiSessionsRoute,
} as any)
const ApiDocumentsDocumentIdRoute = ApiDocumentsDocumentIdRouteImport.update({
  id: '/$documentId',
  path: '/$documentId',
  getParentRoute: () => ApiDocumentsRoute,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/chat': typeof ApiChatRoute
  '/api/documents': typeof ApiDocumentsRouteWithChildren
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/documents/$documentId': typeof ApiDocumentsDocumentIdRoute
  '/api/sessions/$sessionId': typeof ApiSessionsSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/chat': typeof ApiChatRoute
  '/api/documents': typeof ApiDocumentsRouteWithChildren
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/documents/$documentId': typeof ApiDocumentsDocumentIdRoute
  '/api/sessions/$sessionId': typeof ApiSessionsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/chat': typeof ApiChatRoute
  '/api/documents': typeof ApiDocumentsRouteWithChildren
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/documents/$documentId': typeof ApiDocumentsDocumentIdRoute
  '/api/sessions/$sessionId': typeof ApiSessionsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/login'
    | '/register'
    | '/api/chat'
    | '/api/documents'
    | '/api/sessions'
    | '/api/auth/login'
    | '/api/auth/register'
    | '/api/documents/$documentId'
    | '/api/sessions/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/login'
    | '/register'
    | '/api/chat'
    | '/api/documents'
    | '/api/sessions'
    | '/api/auth/login'
    | '/api/auth/register'
    | '/api/documents/$documentId'
    | '/api/sessions/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/login'
    | '/register'
    | '/api/chat'
    | '/api/documents'
    | '/api/sessions'
    | '/api/auth/login'
    | '/api/auth/register'
    | '/api/documents/$documentId'
    | '/api/sessions/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiDocumentsRoute: typeof ApiDocumentsRouteWithChildren
  ApiSessionsRoute: typeof ApiSessionsRouteWithChildren
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions': {
      id: '/api/sessions'
      path: '/api/sessions'
      fullPath: '/api/sessions'
      preLoaderRoute: typeof ApiSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents': {
      id: '/api/documents'
      path: '/api/documents'
      fullPath: '/api/documents'
      preLoaderRoute: typeof ApiDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions/$sessionId': {
      id: '/api/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/api/sessions/$sessionId'
      preLoaderRoute: typeof ApiSessionsSessionIdRouteImport
      parentRoute: typeof ApiSessionsRoute
    }
    '/api/documents/$documentId': {
      id: '/api/documents/$documentId'
      path: '/$documentId'
      fullPath: '/api/documents/$documentId'
      preLoaderRoute: typeof ApiDocumentsDocumentIdRouteImport
      parentRoute: typeof ApiDocumentsRoute
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiDocumentsRouteChildren {
  ApiDocumentsDocumentIdRoute: typeof ApiDocumentsDocumentIdRoute
}

const ApiDocumentsRouteChildren: ApiDocumentsRouteChildren = {
  ApiDocumentsDocumentIdRoute: ApiDocumentsDocumentIdRoute,
}

const ApiDocumentsRouteWithChildren = ApiDocumentsRoute._addFileChildren(
  ApiDocumentsRouteChildren,
)

interface ApiSessionsRouteChildren {
  ApiSessionsSessionIdRoute: typeof ApiSessionsSessionIdRoute
}

const ApiSessionsRouteChildren: ApiSessionsRouteChildren = {
  ApiSessionsSessionIdRoute: ApiSessionsSessionIdRoute,
}

const ApiSessionsRouteWithChildren = ApiSessionsRoute._addFileChildren(
  ApiSessionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiChatRoute: ApiChatRoute,
  ApiDocumentsRoute: ApiDocumentsRouteWithChildren,
  ApiSessionsRoute: ApiSessionsRouteWithChildren,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
